---
title: "classifying-subfamilies"
output: html_document
---

Let's look at some examples.

```{r load-data}
# process-ipums-cps.R
#
# This script  reads data from the "ipums-cps" table in `/db/ipums-raw.duckdb` and writes processed
# data to the "ipums-cps-bucketed" table in `/db/ipums-processed.duckdb`.
#
# ----- Step 0: Configuration ----- #
library("dplyr")
library("duckdb")
library("ipumsr")
library("dbplyr")
library("lubridate")

devtools::load_all("../demographr")

# ----- Step 1: Connect to the database ----- #

con <- dbConnect(duckdb::duckdb(), "data/db/ipums_cps.duckdb")
ipums_db <- tbl(con, "ipums-cps")

```

```{r wrangle-data}
ipums_household <- ipums_db |>
  mutate(hhid = paste(YEAR, MONTH, SERIAL, sep = "-")) |>
  collect() |>
  mutate(
    date = make_date(YEAR, MONTH, 1) |> format("%B %Y"),
    relate_encoded = case_when(
      RELATE == 101 ~ "HOH",
      RELATE %in% c(201, 202, 203) ~ "Spouse",
      RELATE == 301 ~ "Child",
      RELATE == 303 ~ "Stepchild",
      RELATE == 501 ~ "Parent",
      RELATE == 701 ~ "Sibling",
      RELATE == 901 ~ "Grandchild",
      RELATE == 1001 ~ "Other relative",
      RELATE == 1113 ~ "Partner / Roommate",
      RELATE %in% c(1114, 1116, 1117) ~ "Unmarried partner",
      RELATE == 1115 ~ "Housemate / roommate",
      RELATE == 1241 ~ "Roomer / boarder / lodger",
      RELATE == 1242 ~ "Foster child",
      RELATE == 1260 ~ "Other nonrelative"
    ),
    sex_encoded = case_when(
      SEX == 1 ~ "Male",
      SEX == 2 ~ "Female"
    )
  ) |>
  select(CPSID, date, NUMPREC, PERNUM, relate_encoded, AGE, sex_encoded, MOMLOC, PELNMOM, POPLOC, PELNDAD, NSIBS, SPLOC, ASPOUSE, PECOHAB,   LINENO)

# View one household
view_one_hh <- function(hh_id) {
 ipums_household |>
  filter(CPSID == rand_id) |>
  collect()
}

```

Here's 2 parents with 4 young children

```{r}
view_one_hh(20250104270900)
```